name:                hastermind
version:             0.1.0.0
github:              "EduardoLR10/hastermind"
license:             BSD3
author:              "Eduardo Lemos Rocha"
maintainer:          "dudulr10@gmail.com"
copyright:           "2022 DApp360 Cohort 1"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/hastermind#readme>

dependencies:
- base >= 4.7 && < 5
- mtl
- random
- errors
- transformers
- time

library:
  source-dirs: src

executables:
  hastermind-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hastermind

tests:
  hastermind-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hastermind
